# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10AUC7lKQUaceVzkzSt3yujr_P-qDtrdf
"""

import streamlit as st
import numpy as np
from pytorch_tabnet.tab_model import TabNetClassifier
from sklearn.preprocessing import StandardScaler, LabelEncoder
import joblib

st.title("🧪 Talasemi Sınıflandırıcı")
st.write("Aşağıdaki formu doldurarak bir hastaya ait tahmini görebilirsiniz.")

# Özellik girişleri (kendi veri setinden alındı)
features = {
    "'Hb": st.number_input("Hemoglobin (Hb)", 0.0, 20.0, step=0.1),
    "MCV": st.number_input("MCV", 40.0, 120.0, step=0.1),
    "MCH": st.number_input("MCH", 10.0, 40.0, step=0.1),
    "'Hb.1": st.number_input("Hb1 (%)", 0.0, 100.0),
    "'Hb.2": st.number_input("Hb2 (%)", 0.0, 100.0),
    "'Hb.3": st.number_input("Hb3 (%)", 0.0, 100.0),
    "'Hb.4": st.number_input("Hb4 (%)", 0.0, 100.0),
    "'Hb.5": st.number_input("Hb5 (%)", 0.0, 100.0)
}

input_array = np.array([list(features.values())])

# Model ve scaler yükleme
@st.cache_resource
def load_model_and_utils():
    model = TabNetClassifier()
    model.load_model("tabnet_model.zip")
    scaler = joblib.load("scaler.pkl")
    label_encoder = joblib.load("label_encoder.pkl")
    return model, scaler, label_encoder

if st.button("Tahmin Et"):
    model, scaler, label_encoder = load_model_and_utils()

    # Ön işleme
    input_scaled = scaler.transform(input_array)
    pred = model.predict(input_scaled)
    label = label_encoder.inverse_transform(pred)[0]

    st.success(f"🧬 Tahmin Edilen Durum: **{label}**")